[package]
name = "icu"
edition = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
publish = false
license-file = { workspace = true }

[features]
default = []
ic = []

[dependencies]
candid = { workspace = true }
defer = { workspace = true }
derive_more = { workspace = true }
ic-cdk = { workspace = true }
ic-cdk-timers = { workspace = true }
ic-ledger-types = { workspace = true }
ic-stable-structures = { workspace = true }
icrc-ledger-types = { workspace = true }
minicbor-serde = { workspace = true }
remain = { workspace = true }
serde = { workspace = true }
num-traits = { workspace = true }
serde_bytes = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
tinyrand = { workspace = true }
toml = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
futures = "0.3"

[[bench]]
name = "serialize"
harness = false

[lints]
workspace = true
