[package]
name = "skynet_memory_cell"
edition = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
publish = false
build = "../build.rs"
description = "Skynet memory-cell sharding console"

[package.metadata.cargo-machete]
ignored = ["candid"]

[package.metadata.canic]
app = "skynet"
role = "memory_cell"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = { workspace = true }
canic = { workspace = true, features = ["metrics"] }
ic-cdk = { workspace = true }
skynet_console = { workspace = true }

[build-dependencies]
canic = { workspace = true, features = [] }

[lints]
workspace = true
