[package]
name = "saltz_burner"
edition = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
publish = false
build = "build.rs"
description = "Standalone bounded cycle-burn waveform canister"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
candid = { workspace = true }
ic-cdk = { workspace = true }
ic-timers = { workspace = true }
serde = { workspace = true, features = ["derive"] }

[build-dependencies]
saltz_simulator = { path = "../simulator" }

[dev-dependencies]
ic-testkit = { workspace = true }
pocket-ic = "15.0.0"

[lints]
workspace = true
