[package]
name = "canic_icydb_lifecycle_probe"
edition = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
publish = false

[package.metadata.canic]
app = "canic_icydb_lifecycle_probe"
role = "test"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = { workspace = true }
canic = { workspace = true, features = [] }
ic-cdk = { workspace = true }
ic-timers = { workspace = true }
icydb = { version = "0.245", default-features = false }

[build-dependencies]
canic = { workspace = true, features = [] }
canic-icydb-lifecycle-schema = { workspace = true }
icydb = { version = "0.245", default-features = false }

[lints]
workspace = true
