controllers = []
app_index = []

[subnets.prime]

[subnets.prime.canisters.root]
kind = "root"

[subnets.prime.canisters.scale_hub]
kind = "singleton"

[subnets.prime.canisters.scale_hub.scaling.pools.scales]
canister_role = "scale_replica"
policy.initial_workers = 0
policy.min_workers = 2

[subnets.prime.canisters.scale_replica]
kind = "replica"
