controllers = []
[services.fleet]
roles = []

[app]
name = "scaling_probe"

[roles.root]
kind = "root"
package = "../root_probe"

[roles.scale_hub]
kind = "canister"
package = "."

[roles.scale_replica]
kind = "canister"
package = "../../../apps/test/scale"

[auth.delegated_tokens]
enabled = false

[subnets.default]

[subnets.default.canisters.root]
kind = "root"

[subnets.default.canisters.scale_hub]
kind = "service"

[subnets.default.canisters.scale_hub.scaling.pools.scales]
canister_role = "scale_replica"
policy.initial_workers = 0
policy.min_workers = 2

[subnets.default.canisters.scale_replica]
kind = "replica"
