controllers = []

[reserve]
minimum_size = 3

#################### canisters

# ----------------------------------
# blank
# ----------------------------------
[canisters.blank]
auto_create = true
topup.threshold = "10T"
topup.amount = "5T"


# ----------------------------------
# Delegation
# ----------------------------------
[canisters.delegation]
auto_create = true
uses_directory = true
delegation = true
topup.amount = "5T"
topup.threshold = "10T"


# ---------------------------
# Elastic
# ---------------------------
[canisters.elastic_hub]
auto_create = true
uses_directory = true
topup.threshold = "10T"
topup.amount = "5T"

[canisters.elastic_hub.elastic.pools.workers]
canister_type = "elastic"

[canisters.elastic]
topup.threshold = "10T"
topup.amount = "5T"


# ---------------------------
# Sharding
# ---------------------------
[canisters.shard_hub]
auto_create = true
uses_directory = true
topup.threshold = "10T"
topup.amount = "5T"

[canisters.shard_hub.sharding.pools.shards]
canister_type = "shard"
policy.initial_capacity = 100
policy.max_shards = 64
policy.growth_threshold_pct = 80

[canisters.shard]
topup.threshold = "10T"
topup.amount = "5T"


#####################################

[standards]
icrc21 = true
