controllers = [
    "bn6wo-xpofx-5va6n-knhsi-d26er-6oxej-a5m3i-i5yh7-h3il7-s65zr-lae", # gabriel
    "unn7e-de5sw-3kw5b-bjyrh-qjhmf-25uhy-niapa-hgtov-qkwwx-lxqpn-gae", # rem
]

[pool]
minimum_size = 10

[canisters.example]
auto_create = 2
initial_cycles = "6T"
uses_directory = false
topup.threshold = "10T"
topup.amount = "5T"

[standards]
icrc21 = true
