controllers = []

[pool]
minimum_size = 3

#################### canisters

# ----------------------------------
# blank
# ----------------------------------
[canisters.blank]
auto_create = true
initial_cycles = "6T"
topup.threshold = "10T"
topup.amount = "5T"


# ----------------------------------
# delegation
# ----------------------------------
[canisters.delegation]
auto_create = true
uses_directory = true
delegation = true
topup.amount = "5T"
topup.threshold = "10T"


# ----------------------------------
# sharder
# ----------------------------------
[canisters.sharder]
auto_create = true
uses_directory = true
topup.threshold = "10T"
topup.amount = "5T"

[canisters.sharder.sharder]

[canisters.sharder.sharder.pools.shards]
canister_type = "shard"
policy.initial_capacity = 100
policy.max_shards = 64
policy.growth_threshold_pct = 80


# ----------------------------------
# shard
# ----------------------------------
[canisters.shard]
initial_cycles = "6T"
topup.threshold = "10T"
topup.amount = "5T"

#####################################

[standards]
icrc21 = true
