[package]
name = "canic-fleet-root"
edition = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
license = { workspace = true }
description = "Canonical Canic Fleet Subnet Root canister crate"
readme = "README.md"
documentation = "https://docs.rs/canic-fleet-root"
homepage = { workspace = true }
repository = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }
publish = true

[package.metadata.cargo-machete]
ignored = ["candid", "ic-cdk"]

[package.metadata.canic]
app = "fleet_root"
role = "root"

[lib]
name = "canic_fleet_root"
crate-type = ["cdylib"]

[dependencies]
candid = { workspace = true }
canic = { workspace = true, default-features = false, features = ["control-plane"] }
ic-cdk = { workspace = true }

[build-dependencies]
canic = { workspace = true, features = [] }

[lints]
workspace = true
