/// Public wire-level endpoint names for Canic canisters.
///
/// `canic_core::protocol` is intentionally the smaller runtime-internal subset
/// used by orchestration code. This facade module keeps the wider convenience
/// table for tests, tooling, and downstream callers.
pub use canic_core::protocol::{
    BLOB_STORAGE_069_GATEWAY_METHODS, BLOB_STORAGE_070_CASHIER_METHODS,
    BLOB_STORAGE_070_GATEWAY_METHODS, BLOB_STORAGE_BLOBS_ARE_LIVE, BLOB_STORAGE_BLOBS_TO_DELETE,
    BLOB_STORAGE_CASHIER_ACCOUNT_BALANCE_GET_V1, BLOB_STORAGE_CASHIER_ACCOUNT_TOP_UP_V1,
    BLOB_STORAGE_CASHIER_STORAGE_GATEWAY_PRINCIPAL_LIST_V1, BLOB_STORAGE_CONFIRM_BLOB_DELETION,
    BLOB_STORAGE_CREATE_CERTIFICATE, BLOB_STORAGE_FUND_FROM_PROJECT_CYCLES, BLOB_STORAGE_STATUS,
    BLOB_STORAGE_UPDATE_GATEWAY_PRINCIPALS, CANIC_ACTIVATE_FLEET,
    CANIC_ACTIVE_DELEGATION_PROOF_STATUS, CANIC_COMPONENT_RUNTIME_ACTIVATE,
    CANIC_COMPONENT_RUNTIME_DIRECTORY_PREPARE, CANIC_COMPONENT_RUNTIME_DIRECTORY_SYNCHRONIZE,
    CANIC_COMPONENT_RUNTIME_STATUS, CANIC_CYCLE_BALANCE, CANIC_CYCLE_TRACKER,
    CANIC_FLEET_ACTIVATION_STATUS, CANIC_FLEET_REGISTRY, CANIC_FLEET_REGISTRY_ACKNOWLEDGE_ROOT,
    CANIC_FLEET_REGISTRY_ACTIVATE, CANIC_FLEET_REGISTRY_ACTIVATE_MIRROR,
    CANIC_FLEET_REGISTRY_MANIFEST, CANIC_FLEET_REGISTRY_MIRROR_STATUS,
    CANIC_FLEET_REGISTRY_PUBLISH_ROOT_DRAINING, CANIC_FLEET_REGISTRY_ROOT_ACKNOWLEDGEMENTS,
    CANIC_FLEET_REGISTRY_SNAPSHOT_FOR_ROOT, CANIC_FLEET_REGISTRY_SYNC_STATUS,
    CANIC_FLEET_REGISTRY_SYNCHRONIZE, CANIC_FLEET_REGISTRY_VERSION,
    CANIC_FLEET_SUBNET_ROOT_AUTHORITY, CANIC_FLEET_SUBNET_ROOT_CANISTER_SUMMARY,
    CANIC_FLEET_SUBNET_ROOT_DRAINING_BEGIN, CANIC_FLEET_SUBNET_ROOT_DRAINING_STATUS,
    CANIC_FLEET_SUBNET_ROOT_JOIN, CANIC_GET_DELEGATED_TOKEN,
    CANIC_GET_OR_CREATE_CHAIN_KEY_DELEGATION_PROOF, CANIC_GET_ROLE_ATTESTATION, CANIC_HEALTH,
    CANIC_INSTALL_ACTIVE_DELEGATION_PROOF, CANIC_MANAGED_CANISTER_BINDING, CANIC_METADATA,
    CANIC_PREPARE_DELEGATED_TOKEN, CANIC_PREPARE_FLEET_ACTIVATION,
    CANIC_PREPARE_FLEET_CREDENTIAL_GENERATION, CANIC_PREPARE_ROLE_ATTESTATION, CANIC_READINESS,
    CANIC_RESPONSE_CAPABILITY_V1, CANIC_RESUME_FLEET_ACTIVATION, CANIC_ROOT_COMPONENT_ALLOCATE,
    CANIC_ROOT_COMPONENT_ALLOCATION_STATUS, CANIC_ROOT_COMPONENT_CHILD_ALLOCATE,
    CANIC_ROOT_COMPONENT_CHILD_ALLOCATION_STATUS, CANIC_ROOT_COMPONENT_CHILD_COMMIT,
    CANIC_ROOT_COMPONENT_CHILD_CREATE, CANIC_ROOT_COMPONENT_CHILD_DIRECTORY_PREPARE,
    CANIC_ROOT_COMPONENT_CHILD_INSTALL, CANIC_ROOT_COMPONENT_CHILD_MEMBERSHIP_ACTIVATE,
    CANIC_ROOT_COMPONENT_CHILD_RUNTIME_ACTIVATE, CANIC_ROOT_COMPONENT_COMMIT,
    CANIC_ROOT_COMPONENT_CREATE, CANIC_ROOT_COMPONENT_DELETE, CANIC_ROOT_COMPONENT_DELETION_STATUS,
    CANIC_ROOT_COMPONENT_DIRECTORY_HEAD, CANIC_ROOT_COMPONENT_DIRECTORY_PAGE,
    CANIC_ROOT_COMPONENT_DIRECTORY_PREPARE, CANIC_ROOT_COMPONENT_DRAINING_ADVANCE,
    CANIC_ROOT_COMPONENT_DRAINING_BEGIN, CANIC_ROOT_COMPONENT_DRAINING_INVENTORY_FINALIZE,
    CANIC_ROOT_COMPONENT_DRAINING_STATUS, CANIC_ROOT_COMPONENT_INSTALL,
    CANIC_ROOT_COMPONENT_MEMBERSHIP_ACTIVATE, CANIC_ROOT_COMPONENT_MEMBERSHIP_REMOVE,
    CANIC_ROOT_COMPONENT_QUIESCE, CANIC_ROOT_COMPONENT_QUIESCENCE_STATUS,
    CANIC_ROOT_COMPONENT_REGISTRY_PARTITION, CANIC_ROOT_COMPONENT_REGISTRY_PREPARE,
    CANIC_ROOT_COMPONENT_REGISTRY_STATUS, CANIC_ROOT_COMPONENT_RUNTIME_ACTIVATE,
    CANIC_ROOT_COMPONENT_SUBTREE_REMOVAL_ADVANCE, CANIC_ROOT_COMPONENT_SUBTREE_REMOVAL_BEGIN,
    CANIC_ROOT_COMPONENT_SUBTREE_REMOVAL_DELETE,
    CANIC_ROOT_COMPONENT_SUBTREE_REMOVAL_DELETE_PREPARE,
    CANIC_ROOT_COMPONENT_SUBTREE_REMOVAL_DIRECTORY_SYNCHRONIZE,
    CANIC_ROOT_COMPONENT_SUBTREE_REMOVAL_LEAF_FINALIZE,
    CANIC_ROOT_COMPONENT_SUBTREE_REMOVAL_MEMBERSHIP_REMOVE,
    CANIC_ROOT_COMPONENT_SUBTREE_REMOVAL_STATUS, CANIC_ROOT_COMPONENT_SUBTREE_REMOVAL_STOP,
    CANIC_ROOT_COMPONENT_SUBTREE_REMOVAL_STOP_PREPARE, CANIC_ROOT_ISSUER_RENEWAL_STATUS,
    CANIC_ROOT_STORE_BOOTSTRAP, CANIC_ROOT_STORE_BOOTSTRAP_STATUS, CANIC_RUNTIME_STATUS,
    CANIC_SYNC_STATE, CANIC_SYNC_TOPOLOGY, CANIC_TEMPLATE_PREPARE_ADMIN,
    CANIC_TEMPLATE_PUBLISH_CHUNK_ADMIN, CANIC_TEMPLATE_STAGE_MANIFEST_ADMIN,
    CANIC_UPSERT_ROOT_ISSUER_POLICY, CANIC_UPSERT_ROOT_ISSUER_RENEWAL_TEMPLATE,
    CANIC_WASM_STORE_BEGIN_GC, CANIC_WASM_STORE_BOOTSTRAP_DEBUG, CANIC_WASM_STORE_CATALOG,
    CANIC_WASM_STORE_CHUNK, CANIC_WASM_STORE_COMPLETE_GC, CANIC_WASM_STORE_INFO,
    CANIC_WASM_STORE_OVERVIEW, CANIC_WASM_STORE_PREPARE, CANIC_WASM_STORE_PREPARE_GC,
    CANIC_WASM_STORE_PUBLISH_CHUNK, CANIC_WASM_STORE_ROOT_UPDATE_METHODS,
    CANIC_WASM_STORE_STAGE_MANIFEST, CANIC_WASM_STORE_STATUS,
    CANIC_WASM_STORE_STRUCTURAL_QUERY_METHODS,
};

pub const CANIC_FLEET_ADMIN: &str = "canic_fleet_admin";
pub const CANIC_CANISTER_UPGRADE: &str = "canic_canister_upgrade";
pub const CANIC_CANISTER_STATUS: &str = "canic_canister_status";
pub const CANIC_CONFIG: &str = "canic_config";
pub const CANIC_SUBNET_REGISTRY: &str = "canic_subnet_registry";
pub const CANIC_POOL_LIST: &str = "canic_pool_list";
pub const CANIC_POOL_ADMIN: &str = "canic_pool_admin";
pub const CANIC_WASM_STORE_ADMIN: &str = "canic_wasm_store_admin";
pub const ICRC10_SUPPORTED_STANDARDS: &str = "icrc10_supported_standards";
pub const ICRC21_CANISTER_CALL_CONSENT_MESSAGE: &str = "icrc21_canister_call_consent_message";
pub const CANIC_MEMORY_LEDGER: &str = "canic_memory_ledger";
pub const CANIC_ENV: &str = "canic_env";
pub const CANIC_LOG: &str = "canic_log";
pub const CANIC_METRICS: &str = "canic_metrics";
pub const CANIC_READY: &str = "canic_ready";
pub const CANIC_FLEET_STATE: &str = "canic_fleet_state";
pub const CANIC_FLEET_DIRECTORY: &str = "canic_fleet_directory";
pub const CANIC_SUBNET_DIRECTORY: &str = "canic_subnet_directory";
pub const CANIC_CANISTER_CHILDREN: &str = "canic_canister_children";
pub const CANIC_SCALING_REGISTRY: &str = "canic_scaling_registry";
pub const CANIC_SHARDING_REGISTRY: &str = "canic_sharding_registry";
pub const CANIC_SHARDING_PARTITION_KEYS: &str = "canic_sharding_partition_keys";
