/// Public wire-level endpoint names for Canic canisters.
///
/// `canic_core::protocol` is intentionally the smaller runtime-internal subset
/// used by orchestration code. This facade module keeps the wider convenience
/// table for tests, tooling, and downstream callers.
pub use canic_core::protocol::{
    BLOB_STORAGE_069_GATEWAY_METHODS, BLOB_STORAGE_070_CASHIER_METHODS,
    BLOB_STORAGE_070_GATEWAY_METHODS, BLOB_STORAGE_BLOBS_ARE_LIVE, BLOB_STORAGE_BLOBS_TO_DELETE,
    BLOB_STORAGE_CASHIER_ACCOUNT_BALANCE_GET_V1, BLOB_STORAGE_CASHIER_ACCOUNT_TOP_UP_V1,
    BLOB_STORAGE_CASHIER_STORAGE_GATEWAY_PRINCIPAL_LIST_V1, BLOB_STORAGE_CONFIRM_BLOB_DELETION,
    BLOB_STORAGE_CREATE_CERTIFICATE, BLOB_STORAGE_FUND_FROM_PROJECT_CYCLES, BLOB_STORAGE_STATUS,
    BLOB_STORAGE_UPDATE_GATEWAY_PRINCIPALS, CANIC_ACTIVE_DELEGATION_PROOF_STATUS,
    CANIC_CYCLE_BALANCE, CANIC_CYCLE_TRACKER, CANIC_DELEGATION_RENEWAL_PROVISIONERS,
    CANIC_DELEGATION_RENEWAL_WORK, CANIC_GET_DELEGATED_TOKEN, CANIC_GET_DELEGATION_PROOF_BATCH,
    CANIC_GET_DELEGATION_RENEWAL_PROOF_BATCH, CANIC_GET_OR_CREATE_CHAIN_KEY_DELEGATION_PROOF,
    CANIC_GET_ROLE_ATTESTATION, CANIC_INSTALL_ACTIVE_DELEGATION_PROOF,
    CANIC_INSTALL_DELEGATION_PROOF_BATCH, CANIC_METADATA, CANIC_PREPARE_DELEGATED_TOKEN,
    CANIC_PREPARE_DELEGATION_PROOF_BATCH, CANIC_PREPARE_ROLE_ATTESTATION,
    CANIC_RESPONSE_CAPABILITY_V1, CANIC_ROOT_ISSUER_RENEWAL_STATUS, CANIC_SYNC_STATE,
    CANIC_SYNC_TOPOLOGY, CANIC_TEMPLATE_PREPARE_ADMIN, CANIC_TEMPLATE_PUBLISH_CHUNK_ADMIN,
    CANIC_TEMPLATE_STAGE_MANIFEST_ADMIN, CANIC_UPSERT_DELEGATION_RENEWAL_PROVISIONER,
    CANIC_UPSERT_ROOT_ISSUER_POLICY, CANIC_UPSERT_ROOT_ISSUER_RENEWAL_TEMPLATE,
    CANIC_WASM_STORE_BEGIN_GC, CANIC_WASM_STORE_BOOTSTRAP_DEBUG,
    CANIC_WASM_STORE_BOOTSTRAP_RESUME_ROOT_ADMIN, CANIC_WASM_STORE_CATALOG, CANIC_WASM_STORE_CHUNK,
    CANIC_WASM_STORE_COMPLETE_GC, CANIC_WASM_STORE_INFO, CANIC_WASM_STORE_OVERVIEW,
    CANIC_WASM_STORE_PREPARE, CANIC_WASM_STORE_PREPARE_GC, CANIC_WASM_STORE_PUBLISH_CHUNK,
    CANIC_WASM_STORE_ROOT_UPDATE_METHODS, CANIC_WASM_STORE_STAGE_MANIFEST, CANIC_WASM_STORE_STATUS,
    CANIC_WASM_STORE_STRUCTURAL_QUERY_METHODS, canic_wasm_store_method_requires_internal_proof,
};

pub const CANIC_APP: &str = "canic_app";
pub const CANIC_CANISTER_UPGRADE: &str = "canic_canister_upgrade";
pub const CANIC_CANISTER_STATUS: &str = "canic_canister_status";
pub const CANIC_CONFIG: &str = "canic_config";
pub const CANIC_APP_REGISTRY: &str = "canic_app_registry";
pub const CANIC_SUBNET_REGISTRY: &str = "canic_subnet_registry";
pub const CANIC_POOL_LIST: &str = "canic_pool_list";
pub const CANIC_POOL_ADMIN: &str = "canic_pool_admin";
pub const CANIC_WASM_STORE_ADMIN: &str = "canic_wasm_store_admin";
pub const ICRC10_SUPPORTED_STANDARDS: &str = "icrc10_supported_standards";
pub const ICRC21_CANISTER_CALL_CONSENT_MESSAGE: &str = "icrc21_canister_call_consent_message";
pub const CANIC_MEMORY_LEDGER: &str = "canic_memory_ledger";
pub const CANIC_ENV: &str = "canic_env";
pub const CANIC_LOG: &str = "canic_log";
pub const CANIC_METRICS: &str = "canic_metrics";
pub const CANIC_READY: &str = "canic_ready";
pub const CANIC_APP_STATE: &str = "canic_app_state";
pub const CANIC_SUBNET_STATE: &str = "canic_subnet_state";
pub const CANIC_APP_INDEX: &str = "canic_app_index";
pub const CANIC_SUBNET_INDEX: &str = "canic_subnet_index";
pub const CANIC_CANISTER_CHILDREN: &str = "canic_canister_children";
pub const CANIC_SCALING_REGISTRY: &str = "canic_scaling_registry";
pub const CANIC_SHARDING_REGISTRY: &str = "canic_sharding_registry";
pub const CANIC_SHARDING_PARTITION_KEYS: &str = "canic_sharding_partition_keys";
