controllers = []
[app]
name = "standalone"
init_mode = "enabled"


[roles.root]
kind = "root"
package = "../../../apps/test/root"

[roles.minimal_metrics]
kind = "canister"
package = "."

[app.whitelist]

[auth.delegated_tokens]
enabled = false

[tree_specs.default]

[tree_groups.default]
tree_spec = "default"
initial_trees = 1
maximum_trees = 1

[tree_specs.default.canisters.root]
kind = "root"

[tree_specs.default.canisters.minimal_metrics]
kind = "service"

[tree_specs.default.canisters.minimal_metrics.metrics]
profile = "leaf"
