controllers = []
[app]
name = "standalone"
init_mode = "enabled"


[roles.root]
kind = "root"
package = "../../../apps/test/root"

[roles.minimal_metrics]
kind = "canister"
package = "."

[app.whitelist]

[auth.delegated_tokens]
enabled = false

[component_specs.default]
component_role = "minimal_metrics"
maximum_instances = 1

[component_specs.default.metrics]
profile = "leaf"
