controllers = []
app_directory = []

[app]
init_mode = "enabled"

[app.whitelist]

[auth.delegated_tokens]
enabled = true
ecdsa_key_name = "test_key_1"

[standards]
icrc21 = true

[subnets.prime]

[subnets.prime.canisters.root]
kind = "root"

[subnets.prime.canisters.test]
kind = "singleton"

[subnets.prime.canisters.test.delegated_auth]
verifier = true
