[workspace]
members = ["."]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.91.0"
license = "MIT"

[workspace.dependencies]
candid = "0.10.36"
canic = { path = "../../../crates/canic", default-features = false }
canic-blob-service = { version = "0.1.0", path = ".." }
ic-cdk = "0.20.3"

[package]
name = "blob-service-consumer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[package.metadata.canic]
app = "consumer-app"
role = "blob"

[lib]
crate-type = ["cdylib"]
test = false
doctest = false

[dependencies]
candid.workspace = true
canic = { workspace = true, features = [] }
canic-blob-service.workspace = true
ic-cdk.workspace = true

[build-dependencies]
canic = { workspace = true, features = [] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"

[profile.fast]
inherits = "release"
lto = "thin"
codegen-units = 8
incremental = false
