[package]
name = "fleet_coordinator_stub"
edition = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = { workspace = true }
canic = { workspace = true, default-features = false, features = ["fleet-coordinator-canister"] }
ic-cdk = { workspace = true }

[lints]
workspace = true
