controllers = []
[app]
name = "standalone"
init_mode = "enabled"


[roles.root]
kind = "root"
package = "../root_probe"

[roles.app]
kind = "canister"
package = "."

[app.whitelist]

[auth.delegated_tokens]
enabled = false

[component_specs.default]
component_role = "app"
maximum_instances = 1
