controllers = []
[services.fleet]
roles = []

[app]
name = "wasm_store"
init_mode = "enabled"


[roles.wasm_store]
kind = "canister"
package = "."

[app.whitelist]

[auth.delegated_tokens]
enabled = false
